Design Entry;SmartDesign Check||(null)||'PROC_SUBSYSTEM' was generated successfully||(null);(null)||(null);(null)
Implementation;Synthesis||VERI-1063||Warning: instantiating unknown module UJTAG||(null);(null)||corejtagdebug.v(166);liberoaction://cross_probe/hdl/file/'C:\Users\hbreslin\Desktop\Project Workspace\My projects\M2S090\M2S150_V02\component\Actel\DirectCore\COREJTAGDEBUG\2.0.100\rtl\vlog\core\corejtagdebug.v'/linenumber/166
Implementation;Synthesis||VERI-1063||Warning: instantiating unknown module CLKINT||(null);(null)||corejtagdebug.v(174);liberoaction://cross_probe/hdl/file/'C:\Users\hbreslin\Desktop\Project Workspace\My projects\M2S090\M2S150_V02\component\Actel\DirectCore\COREJTAGDEBUG\2.0.100\rtl\vlog\core\corejtagdebug.v'/linenumber/174
HelpInfo,C:\Microsemi\synplify_L201609M-2_W\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\synplify_L201609M-2_W\bin\mbin\assistant
Implementation;Synthesis;RootName:PROC_SUBSYSTEM
Implementation;Place and Route;RootName:PROC_SUBSYSTEM
Implementation;Place and Route||(null)||Please refer to the log file for details about 6 Info(s)||PROC_SUBSYSTEM_layout_log.log;liberoaction://open_report/file/PROC_SUBSYSTEM_layout_log.log||(null);(null)
